pid=input("enter product id:")
pname=input("enter product name:")
price=input("enter product price:")
file1=open("file_product","a")
file1.write(pid+",")
file1.write(pname+",")
file1.write(price)
print("product added successfully")
file1.close()